### ISSUE TITLE
Vector - Deploy OSM stack on premise 

### ISSUE THREAD

**Issue by syncush** [MapColonies/conflict-resolution#8]
The system shall be deployed on-prem cloud.

- [ ] Establish Postgres infra
  - [x] Get postgres extensions
- [x] Bundle artifacts 
  - [x] osm-deployment-stack - osm-seed
  - [x] Osmosis container from osm-deployment-stack
  - [x] download italy and swiss data from geofabrik
- [ ] Describe the number of VM instances required for the deployment
- [ ] Order resources
- [ ] Load data of Italy and Switzerland.
- [ ] System checks

**Comment by syncush** [comment]
![postgres_extentions](https://user-images.githubusercontent.com/19842756/90622506-da24df80-e21d-11ea-94e1-fc7313a40750.png)
